.TH INDEX.TS 1 "Version: 0.0.2-beta.3" "JavaScript and TypeScript Toolchain"
.SH NAME
index.ts \- A versatile JavaScript and TypeScript toolchain build system.
.SH SYNOPSIS
.B index.ts
[entryPoints] [OPTIONS]
.SH DESCRIPTION
The index.ts script provides a comprehensive build system for JavaScript and TypeScript applications. It supports a range of features including serving, watching files, and configuring build options for different platforms.

.SH POSITIONALS
.TP
.B entryPoints
The file entryPoints to build (string).

.SH OPTIONS
.TP
.B -h, --help
Show help (boolean).
.TP
.B -n, --node
Build for node platform (boolean) [default: false].
.TP
.B -d, --dev
Array entryPoints to run as development in Node.js (array).
.TP
.B --debug, --db
Array entryPoints to run in Node.js with debug state (array).
.TP
.B -s, --serve
Serve the build folder over HTTP (boolean) [default: false].
.TP
.B -o, --outdir
Output directory (string) [default: "dist"].
.TP
.B --declaration, --de
Add TypeScript declarations (boolean) [default: false].
.TP
.B -w, --watch
Watch for file changes (boolean) [default: false].
.TP
.B -c, --config
Build configuration file (js/ts) (string) [default: "xbuild.config.ts"].
.TP
.B --tsconfig, --tc
Set TypeScript configuration file to use (string) [default: "tsconfig.json"].
.TP
.B -m, --minify
Minify the code (boolean) [default: false].
.TP
.B -b, --bundle
Bundle the code (boolean) [default: false].
.TP
.B --noTypeChecker, --ntc
Skip TypeScript type checking (boolean) [default: false].
.TP
.B --buildOnError, --boe
Continue building even if there are TypeScript type errors (boolean) [default: false].
.TP
.B -v, --version
Show version number (boolean) [default: false].

.SH EXAMPLES
.B Run the build with specified entry points:
.nf
index.ts myEntryPoint.js --dev
.fi
.B Serve the built files:
.nf
index.ts --serve
.fi
.B Build with a custom output directory:
.nf
index.ts --outdir customDir
.fi

.SH SEE ALSO
For more details, visit the project's documentation at [insert documentation URL here].

.SH AUTHOR
Developed by [Your Name or Organization].

.SH LICENSE
This project is licensed under [Your License].
